#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-loofah
Version  : 2.0.2
Release  : 3
URL      : https://rubygems.org/downloads/loofah-2.0.2.gem
Source0  : https://rubygems.org/downloads/loofah-2.0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-hoe-bundler
BuildRequires : rubygem-hoe-debugging
BuildRequires : rubygem-hoe-gemspec
BuildRequires : rubygem-hoe-git
BuildRequires : rubygem-json
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rr

%description
= Loofah {<img src="https://travis-ci.org/flavorjones/loofah.png?branch=master" alt="Build Status" />}[https://travis-ci.org/flavorjones/loofah]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n loofah-2.0.2
gem spec %{SOURCE0} -l --ruby > rubygem-loofah.gemspec

%build
gem build rubygem-loofah.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
loofah-2.0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/loofah-2.0.2 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/loofah-2.0.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/DocumentDecorator/cdesc-DocumentDecorator.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Elements/cdesc-Elements.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/Document/serialize_root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/DocumentFragment/cdesc-DocumentFragment.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/DocumentFragment/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/DocumentFragment/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/DocumentFragment/serialize_root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/DocumentFragment/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/Scrub/allowed_element%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/Scrub/cdesc-Scrub.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/Scrub/scrub_attributes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/Scrub/scrub_css-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/Scrub/scrub_css_attribute-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/WhiteList/cdesc-WhiteList.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/HTML5/cdesc-HTML5.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/FullSanitizer/cdesc-FullSanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/FullSanitizer/sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/WhiteListSanitizer/cdesc-WhiteListSanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/WhiteListSanitizer/sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/WhiteListSanitizer/sanitize_css-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/ActionView/cdesc-ActionView.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/cdesc-Helpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/remove_extraneous_whitespace-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/sanitize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/sanitize_css-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Helpers/strip_tags-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/MetaHelpers/cdesc-MetaHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/ScrubBehavior/Node/cdesc-Node.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/ScrubBehavior/NodeSet/cdesc-NodeSet.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/ScrubBehavior/cdesc-ScrubBehavior.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/cdesc-Scrubber.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/direction-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/html5lib_sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/traverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/traverse_conditionally_bottom_up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubber/traverse_conditionally_top_down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/ScrubberNotFound/cdesc-ScrubberNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Escape/cdesc-Escape.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Escape/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Escape/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/NewlineBlockElements/cdesc-NewlineBlockElements.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/NoFollow/cdesc-NoFollow.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/NoFollow/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/NoFollow/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Prune/cdesc-Prune.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Prune/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Prune/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Strip/cdesc-Strip.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Strip/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Strip/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Unprintable/cdesc-Unprintable.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Unprintable/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Unprintable/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Whitewash/cdesc-Whitewash.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Whitewash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/Whitewash/scrub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/cdesc-Scrubbers.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/Scrubbers/scrubber_symbols-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/TextBehavior/cdesc-TextBehavior.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/TextBehavior/inner_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/TextBehavior/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/TextBehavior/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/TextBehavior/to_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/XML/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/XML/DocumentFragment/cdesc-DocumentFragment.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/XML/DocumentFragment/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/XML/cdesc-XML.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/cdesc-Loofah.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/fragment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/remove_extraneous_whitespace-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/scrub_document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/scrub_fragment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/scrub_xml_document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/scrub_xml_fragment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/xml_document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/Loofah/xml_fragment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/page-CHANGELOG_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/page-MIT-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/loofah-2.0.2/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/MIT-LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/benchmark/benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/benchmark/fragment.html
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/benchmark/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/benchmark/www.slashdot.com.html
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/elements.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/html/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/html/document_fragment.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/html5/scrub.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/html5/whitelist.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/instance_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/metahelpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/scrubber.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/scrubbers.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/xml/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/lib/loofah/xml/document_fragment.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/assets/testdata_sanitizer_tests1.dat
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/html5/test_sanitizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/integration/test_ad_hoc.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/integration/test_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/integration/test_html.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/integration/test_scrubbers.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/integration/test_xml.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/unit/test_api.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/unit/test_encoding.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/unit/test_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/unit/test_scrubber.rb
/usr/lib64/ruby/gems/2.2.0/gems/loofah-2.0.2/test/unit/test_scrubbers.rb
/usr/lib64/ruby/gems/2.2.0/specifications/loofah-2.0.2.gemspec
